#!/bin/bash

SYS_PREFIX=$(python -c "import sys; import os; print(os.path.dirname(sys.executable))")
gfortran src/salt_study.f -o $SYS_PREFIX/salt_study
jupyter serverextension enable voila --sys-prefix
